Django/day19/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

Django/day19/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.article_list, name="article_list"),
    path('<int:article_id>/', views.article_detail, name="article_detail"),
    path('new/', views.new_article, name="new_article"),
    path('<int:article_id>/edit/', views.edit_article, name="edit_article"),
    path('<int:article_id>/comments/new', views.new_comment, name="new_comment"),
    path('<int:article_id>/like/', views.toggle_like, name="toggle_like"), # board/1/like
]

Django/day19/django_advance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('board/', include('board.urls')),
]

Django/day19/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    address = models.CharField(max_length=200)
    fans = models.ManyToManyField('self', related_name='stars')

Django/day19/board/models.py
from django.db import models
from faker import Faker
from django.conf import settings
f = Faker()

# Create your models here.
class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    keyword = models.CharField(max_length=50)
    email = models.CharField(max_length=200)
    content = models.TextField()
    datetime = models.DateField(blank=True, null=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles') # article _set

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @classmethod
    def dummy(cls, n):
        # article = cls(); 
        # article.title='asdf'
        # article.content='..'
        # ...
        # article.save()
        for i in range(n):
            cls.objects.create(
                title=f.text(20),
                content=f.text(),
                keyword=f.company(),
                email=f.email(),
            )

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=300)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Django/day19/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User


class CustomUserCreationForm(UserCreationForm):
    address = forms.CharField(min_length=3)
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('address', )

class CustomAuthenticationForm(AuthenticationForm):
    class Meta(AuthenticationForm):
        model = User

Django/day19/board/forms.py
from django import forms
# from django.db import models
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    # ModelForm, Meta, model, fields 그대로 써야함.
    
    # 미세 조정 (브라우저단에서 제한하는것. 속성 지우면 서버로 넘어감.)
    title = forms.CharField(min_length=2, strip=True) # 최소 문자수 설정, 앞뒤 띄어쓰기한것 자르기(왜 필요? 서버단에서는 1바이트도 돈이다.)
    email = forms.EmailField()
    keyword = forms.CharField(min_length=1, max_length=10)
    class Meta:
        model = Article
        # fields = '__all__' # 모든 컬럼
        # 원하는 컬럼만 표현하고 싶을때
        # fields = ('title', 'content')
        # 
        ###########################3
        # date만 빼고 싶을때 
        exclude = ['datetime','author','like_users']

class CommentForm(forms.ModelForm):
    content = forms.CharField(min_length=1, max_length=200)
    class Meta:
        model = Comment
        fields = ['content', ]

Django/day19/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login, logout as auth_logout

from .forms import CustomAuthenticationForm, CustomUserCreationForm

def follow(request, user_id):
    fan = request.user
    star = get_object_or_404(id=user_id)
    if fan.stars.filter(id=star.id).exists():
        fan.stars.remove(star)
    else:
        fan.stars.add(star)
    return redirect('accounts:user_detail', star.id)

def signup(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = CustomUserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                auth_login(request, user)
                return redirect('board:article_list')
        else: # GET
            form = CustomUserCreationForm()
        context = {
            'form': form,
        }
        return render(request, 'accounts/signup.html', context)
    else:
        return redirect('board:article_list')

def login(request):
    if request.user.is_authenticated:
        return redirect('board:article_list')
    else:
        if request.method == 'POST':
            form = CustomAuthenticationForm(request, request.POST)
            if form.is_valid():
                user = form.get_user()
                auth_login(request, user)
                return redirect(request.GET.get('next') or 'board:article_list')
        else: # GET
            form = CustomAuthenticationForm()
        context = {
            'form': form,
        }
        return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('board:article_list')

Django/day19/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_POST


# Create your views here.
@login_required
def new_article(request):
    if request.method == 'POST':
        # 사용자가 제출한 후
        # pass
        form = ArticleForm(request.POST) # POST로 온 데이터 알아서 각각 넣어줌
        if form.is_valid(): # 데이터 유효한지 검사
            article = form.save(commit=False)
            article.author = request.user
            article = form.save()
            return redirect('board:article_detail', article.id)
    else: # GET
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'board/article_form.html', context)

@require_GET
def article_list(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'board/article_list.html', context)

def article_detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    # article = Article.objects.get(pk=article_id) # pk=article_id | id=article_id
    comment_form = CommentForm()
    comments = Comment.objects.all()
    if request.user.is_authenticated:
        is_like = article.like_users.filter(id=request.user.id).exists()
    else:
        is_like = None
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
        'is_like': is_like
    }
    return render(request, 'board/article_detail.html', context)

@login_required
def edit_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article) # 
        if form.is_valid(): # 데이터 유효한지 검사
            article = form.save()
            return redirect('board:article_detail', article.id)
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form,
    }
    return render(request, 'board/article_form.html', context)

@login_required
@require_POST
def new_comment(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.article = article
        comment.save()
    return redirect('board:article_detail', article.id)

@require_POST
def toggle_like(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    user = request.user
    if article.like_users.filter(id=user.id).exists():
        # if user in article.like_users.all():
        article.like_users.remove(user)
    else:
        article.like_users.add(user)
    return redirect('board:article_detail', article.id)

Django/day19/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1>Login</h1>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary">
        Login
    </button>
</form>
{% endblock %}

Django/day19/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1>Signup</h1>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary">
        Signup
    </button>
</form>
{% endblock content %}

Django/day19/board/templates/board/article_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1>{{article.title}}</h1>
<h2>{{ article.author }}</h2>

{% if article.author == request.user %}
<a href="">수정</a>
<a href="">삭제</a>
{% endif %}

<small>{{ article.created_at }} | {{ article.updated_at }}</small>

<form action="{% url 'board:toggle_like' article.id %}" method="POST">
    {% csrf_token %}
    {% if is_like %}
    <button class="btn btn-warning">dislike</button>
    {% else %}
    <button class="btn btn-primary">like it!</button>
    {% endif %}
</form>

<p>{{article.content}}</p>

<p>
    {{ article.keyword }} | {{ article.email }}
</p>

{% if user.is_authenticated %}
<form action="{% url 'board:new_comment' article.id %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <button class="btn btn-secondary">댓글 작성</button>
</form>
{% else %}
로그인 하세요!
{% endif %}


{% for comment in comments %}
{% if comment.article_id == article.id %}

    <div>
        {{comment.content}} - {{comment.author}}
    </div>
{% endif %}
{% empty %}
<div>댓글이 없어요</div>
{% endfor %}

{% endblock content %}

Django/day19/board/templates/board/article_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form%}
    
    <input type="submit">
</form>
{% endblock content %}

Django/day19/board/templates/board/article_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Article List</h1>
<h2><a href="{% url 'board:new_article' %}">New Article</a></h2>
<ul>
    {% for article in articles %}
    <li>
        <a href="{% url 'board:article_detail' article.id %}">
            {{article.title}}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock content %}

Django/day19/board/templates/board/new_article.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h1>New Article</h1>
<form action="{% url 'board:new_article' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form%}
    
    <input type="submit">
</form>
{% endblock content %}